project:
  type: book
  title: "Henderson's Statistics Notes for Data Science"

format:
  html:
    theme: cosmo # Use a simple, clean theme for now
    toc: true    # Enable a table of contents
    toc-depth: 2 # Set the depth of the table of contents
    number-sections: true # Number the sections
    #chapter-level: 1  # Ensure chapters are properly numbered starting from "1"
    css: styles.css

book:
  author: 
    - name: "Kristin Henderson"
      affiliation: "SMU MSDS Program"
      orcid: "0000-0002-9265-7709"
  chapters:
    - index.qmd  # Introduction or preface
    - part: "Statistical Foundations"
      chapters:
        - foundation-chapter01.qmd  # Add additional chapters as they are created
        - foundation-chapter02.qmd
        - foundation-chapter03.qmd
        - foundation-chapter04.qmd
        - foundation-chapter05.qmd
        - foundation-chapter06.qmd
        - foundation-chapter07.qmd
        - foundation-chapter08.qmd
        - foundation-chapter09.qmd
        - foundation-chapter10.qmd
        - foundation-chapter11.qmd
        - foundation-chapter12.qmd
        - foundation-chapter13.qmd
    - part: "Applied Statistics"
      chapters:
          - applied-chapter01.qmd
          - applied-chapter02.qmd
          - applied-chapter03.qmd
          - applied-chapter04.qmd
          - applied-chapter05.qmd
          - applied-chapter06.qmd
          #- applied-chapter07.qmd
