project:
  type: book
  title: "Henderson's Statistics Notes for Data Science"

bibliography: references.bib 
biblio-title: References 
link-citations: true
link-bibliography: true
# csl: apa-6th-edition.csl
# license: "CC BY-SA"

format:
  html:
    theme: cosmo # Use a simple, clean theme for now
    toc: true    # Enable a table of contents
    toc-depth: 2 # Set the depth of the table of contents
    number-sections: false # true # Number the sections
    #number-depth: 3
    #chapter-level: 1  # Ensure chapters are properly numbered starting from "1"
    code-fold: true
    css: styles.css

book:
  author: 
    - name: "Kristin Henderson"
      affiliation: "SMU MSDS Program"
      orcid: "0000-0002-9265-7709"
      email: kdhenderson@gmail.com
      corresponding: true
  date: last-modified
  chapters:
    - index.qmd  # Introduction or preface
    - part: "Statistical Foundations"
      chapters:
        - foundation-chapter01.qmd  # Add additional chapters as they are created
        - foundation-chapter02.qmd
        - foundation-chapter03.qmd
        - foundation-chapter04.qmd
        - foundation-chapter05.qmd
        - foundation-chapter06.qmd
        - foundation-chapter07.qmd
        - foundation-chapter08.qmd
        - foundation-chapter09.qmd
        - foundation-chapter10.qmd
        - foundation-chapter11.qmd
        - foundation-chapter12.qmd
        - foundation-chapter13.qmd
        - foundation-review-questions.qmd
    - part: "Applied Statistics"
      chapters:
          - applied-chapter01.qmd
          - applied-chapter02.qmd
          - applied-chapter03.qmd
          - applied-chapter04.qmd
          - applied-chapter05.qmd
          - applied-chapter06.qmd
          - applied-chapter07.qmd
          - applied-chapter08.qmd
          - applied-chapter09.qmd
          - applied-chapter10.qmd
          #- applied-chapter11.qmd
