project:
  type: book
  title: "Henderson's Statistics Notes"

format:
  html:
    theme: cosmo # Use a simple, clean theme for now
    toc: true    # Enable a table of contents
    toc-depth: 2 # Set the depth of the table of contents
    number-sections: true # Number the sections
    #chapter-level: 1  # Ensure chapters are properly numbered starting from "1"
    css: styles.css

book:
  author: 
    - name: "Kristin Henderson"
      affiliation: "SMU MSDS Program"
      orcid: "0000-0002-9265-7709"
  chapters:      # Define the chapters of your book
    - index.qmd  # Introduction or preface
    - chapter01.qmd  # Add additional chapters as they are created
    - chapter02.qmd
    - chapter03.qmd
    - chapter04.qmd
    - chapter05.qmd
    #- chapter06.qmd
    #- chapter07.qmd
    #- chapter08.qmd
    #- chapter09.qmd
    #- chapter10.qmd
    