<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Inferences for Multiple Linear Regression – Henderson's Statistics Notes for Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./foundation-chapter13.html" rel="next">
<link href="./foundation-chapter11.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./foundation-chapter01.html">Statistical Foundations</a></li><li class="breadcrumb-item"><a href="./foundation-chapter12.html"><span class="chapter-title">Inferences for Multiple Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Henderson’s Statistics Notes for Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Henderson’s Statistics Notes</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Drawing Statistical Conclusions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Inference Using T-Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data Screening, Assumptions, and Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Type I, Type II Error, and Power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Alternatives to the T-Tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Comparisons Among Several Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Linear Combinations and the Multiple Comparison Problem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Linear Correlation and Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter09.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Quantifying Uncertainty: Confidence, Prediction and Calibration Intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regression Diagnostics and Model Refinement</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter12.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Inferences for Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-chapter13.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Model Selection and Validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundation-review-questions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Review Questions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Applied Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multiple Linear Regression (MLR) Revisited</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Bias Variance Trade-off</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Bootstrap</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Communicating with Clients</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Matrices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Repeated Measures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Classification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 x 2 Contingency Tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter09.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logistic Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multiple Logistic Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Principal Component Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./applied-chapter12.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Clustering</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-r-code.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Appendix A: R Code Examples for Statistical Foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-sas-code.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Appendix B: SAS Code Examples for Statistical Foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_hypothesis_test_flowchart.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Appendix C: Hypothesis Test Flowchart</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#multiple-linear-regression-mlr-with-a-single-predictor-polynomial-regression" id="toc-multiple-linear-regression-mlr-with-a-single-predictor-polynomial-regression" class="nav-link" data-scroll-target="#multiple-linear-regression-mlr-with-a-single-predictor-polynomial-regression">Multiple Linear Regression (MLR) with a Single Predictor: Polynomial Regression</a></li>
  <li><a href="#coefficient-of-determination-r2" id="toc-coefficient-of-determination-r2" class="nav-link" data-scroll-target="#coefficient-of-determination-r2">Coefficient of Determination (<span class="math inline">\(R^2\)</span>)</a></li>
  <li><a href="#overfitting" id="toc-overfitting" class="nav-link" data-scroll-target="#overfitting">Overfitting</a></li>
  <li><a href="#controlling-for-other-variables-in-mlr" id="toc-controlling-for-other-variables-in-mlr" class="nav-link" data-scroll-target="#controlling-for-other-variables-in-mlr">Controlling for Other Variables in MLR</a></li>
  <li><a href="#overall-f-test" id="toc-overall-f-test" class="nav-link" data-scroll-target="#overall-f-test">Overall F-test</a></li>
  <li><a href="#partial-f-test-extra-sum-of-squares" id="toc-partial-f-test-extra-sum-of-squares" class="nav-link" data-scroll-target="#partial-f-test-extra-sum-of-squares">Partial F-test (Extra Sum of Squares)</a></li>
  <li><a href="#significance-tests-for-each-predictor-t-tests" id="toc-significance-tests-for-each-predictor-t-tests" class="nav-link" data-scroll-target="#significance-tests-for-each-predictor-t-tests">Significance Tests for Each Predictor (<em>t</em>-tests)</a></li>
  <li><a href="#prediction-in-mlr" id="toc-prediction-in-mlr" class="nav-link" data-scroll-target="#prediction-in-mlr">Prediction in MLR</a></li>
  <li><a href="#least-squares-estimates-and-standard-errors" id="toc-least-squares-estimates-and-standard-errors" class="nav-link" data-scroll-target="#least-squares-estimates-and-standard-errors">Least Squares Estimates and Standard Errors</a></li>
  <li><a href="#testing-intercept-and-slope-differences-in-regression-models-bat-echolocation-example" id="toc-testing-intercept-and-slope-differences-in-regression-models-bat-echolocation-example" class="nav-link" data-scroll-target="#testing-intercept-and-slope-differences-in-regression-models-bat-echolocation-example">Testing Intercept and Slope Differences in Regression Models (Bat Echolocation Example)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./foundation-chapter01.html">Statistical Foundations</a></li><li class="breadcrumb-item"><a href="./foundation-chapter12.html"><span class="chapter-title">Inferences for Multiple Linear Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Inferences for Multiple Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<ul>
<li>Interpret inferential statistics for various types of regression models, including those with indicator variables, quadratic terms, and interaction terms.</li>
<li>Interpret and communicate results from a multiple regression analysis.</li>
</ul>
</section>
<section id="multiple-linear-regression-mlr-with-a-single-predictor-polynomial-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-mlr-with-a-single-predictor-polynomial-regression">Multiple Linear Regression (MLR) with a Single Predictor: Polynomial Regression</h2>
<ul>
<li>This is still considered a linear model.
<ul>
<li>It can capture curvilinear trends.<br>
</li>
<li>It is linear in the <span class="math inline">\(\beta_i X^j\)</span> term: for every one-unit increase in <span class="math inline">\(X^j\)</span>, <span class="math inline">\(Y\)</span> changes by a constant <span class="math inline">\(\beta_i\)</span>.<br>
</li>
<li>If the quadratic coefficient is significant but the linear term is not, the linear (lower-order) terms should still be included because they form a singular idea.<br>
</li>
<li>Interpretation can be difficult, especially with higher-order terms.</li>
</ul></li>
<li>In interpreting a quadratic model:
<ul>
<li>The vertex (absolute maximum or minimum) can be found using: <span class="math display">\[
x_{\text{vertex}} = \frac{-\beta_1}{2\beta_2}
\]</span></li>
<li>This value of <span class="math inline">\(X\)</span> represents the point at which <span class="math inline">\(Y\)</span> stops increasing or decreasing, based on the quadratic regression model.</li>
</ul></li>
</ul>
</section>
<section id="coefficient-of-determination-r2" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-of-determination-r2">Coefficient of Determination (<span class="math inline">\(R^2\)</span>)</h2>
<ul>
<li><span class="math inline">\(R^2\)</span> is a measure of effect size for both simple linear regression (SLR) and MLR.</li>
<li>It represents the proportion of variance in the response variable explained by the model.</li>
</ul>
<section id="calculation-in-mlr" class="level3">
<h3 class="anchored" data-anchor-id="calculation-in-mlr">Calculation in MLR</h3>
<ul>
<li><strong>Multiple <span class="math inline">\(R^2\)</span></strong>: This is the squared correlation between the observed values of <span class="math inline">\(Y\)</span> and the predicted values of <span class="math inline">\(Y\)</span>.</li>
<li><strong>Partition of sums of squares</strong>: The total variation in <span class="math inline">\(Y\)</span> (<span class="math inline">\(\text{SS}_{\text{total}}\)</span>) can be split into the variation explained by the model (<span class="math inline">\(\text{SS}_{\text{regression}}\)</span>) and the variation left unexplained (<span class="math inline">\(\text{SS}_{\text{residual}}\)</span>): <span class="math display">\[
\text{SS}_{\text{total}} = \text{SS}_{\text{regression}} + \text{SS}_{\text{residual}}
\]</span> This partition leads to: <span class="math display">\[
R^2 = \frac{\text{SS}_{\text{total}} - \text{SS}_{\text{residual}}}{\text{SS}_{\text{total}}} = \frac{\text{SS}_{\text{regression}}}{\text{SS}_{\text{total}}}
     = 1 - \frac{\text{SS}_{\text{residual}}}{\text{SS}_{\text{total}}}
\]</span></li>
</ul>
</section>
<section id="relationship-with-the-overall-f-test" class="level3">
<h3 class="anchored" data-anchor-id="relationship-with-the-overall-f-test">Relationship with the Overall F-test</h3>
<ul>
<li>The F-test statistic can be rewritten in terms of <span class="math inline">\(R^2\)</span>.<br>
</li>
<li>Testing whether all parameters equal zero is equivalent to testing whether <span class="math inline">\(R^2 = 0\)</span>.</li>
</ul>
</section>
<section id="r2-and-parsimony" class="level3">
<h3 class="anchored" data-anchor-id="r2-and-parsimony"><span class="math inline">\(R^2\)</span> and Parsimony</h3>
<ul>
<li>Adding more predictors will always increase <span class="math inline">\(R^2\)</span>.<br>
</li>
<li>An oversaturated model can have <span class="math inline">\(R^2 = 1\)</span> even if the predictors do not contribute meaningfully.<br>
</li>
<li>The goal is to create a <strong>parsimonious</strong> model—one that is as simple as possible while still maximizing <span class="math inline">\(R^2\)</span>.</li>
</ul>
</section>
<section id="adjusted-r2" class="level3">
<h3 class="anchored" data-anchor-id="adjusted-r2">Adjusted <span class="math inline">\(R^2\)</span></h3>
<ul>
<li>Adjusted <span class="math inline">\(R^2\)</span> accounts for the number of predictors (<span class="math inline">\(k\)</span>) and the sample size (<span class="math inline">\(n\)</span>).</li>
<li>The formula is: <span class="math display">\[
R^2_{\text{adj}} = R^2 - (1 - R^2) \frac{k}{n-k-1}
\]</span></li>
<li>Adjusted <span class="math inline">\(R^2\)</span> penalizes unnecessary predictors and small sample sizes.<br>
</li>
<li>It rewards variables that significantly improve model fit, resulting in a net increase if a predictor explains a substantial proportion of the variance.<br>
</li>
<li>It is generally a better measure of effect size than <span class="math inline">\(R^2\)</span> in MLR.</li>
</ul>
</section>
</section>
<section id="overfitting" class="level2">
<h2 class="anchored" data-anchor-id="overfitting">Overfitting</h2>
<ul>
<li>A value of <span class="math inline">\(R^2\)</span> equal to 1 can always be achieved, but this does not indicate good predictive power.<br>
</li>
<li>Overfitting occurs when the model fits both the noise and the signal in the sample data.<br>
</li>
<li>A high <span class="math inline">\(R^2\)</span> value does not guarantee that the model will generalize well to new data.</li>
</ul>
</section>
<section id="controlling-for-other-variables-in-mlr" class="level2">
<h2 class="anchored" data-anchor-id="controlling-for-other-variables-in-mlr">Controlling for Other Variables in MLR</h2>
<ul>
<li>When we hold <span class="math inline">\(X_2\)</span> constant (i.e., look at a subpopulation with similar <span class="math inline">\(X_2\)</span> values), we can examine the effect of changes in <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span>.</li>
</ul>
</section>
<section id="overall-f-test" class="level2">
<h2 class="anchored" data-anchor-id="overall-f-test">Overall F-test</h2>
<ul>
<li>The overall F-test evaluates whether the model is statistically significant.</li>
<li><strong>Hypotheses</strong>:
<ul>
<li><span class="math inline">\(H_0\)</span>: All slopes are equal to 0 (i.e., <span class="math inline">\(R^2 = 0\)</span>).<br>
</li>
<li><span class="math inline">\(H_a\)</span>: At least one slope is not zero.</li>
</ul></li>
<li><strong>F-statistic formula</strong>: <span class="math display">\[
F = \frac{\text{SS}_{\text{regression}} / k}{\text{SS}_{\text{residual}} / (n - k - 1)} = \frac{\text{MS}_{\text{regression}}}{\text{MS}_{\text{error}}}
\]</span></li>
<li>This test can also be expressed in terms of <span class="math inline">\(R^2\)</span>.</li>
</ul>
</section>
<section id="partial-f-test-extra-sum-of-squares" class="level2">
<h2 class="anchored" data-anchor-id="partial-f-test-extra-sum-of-squares">Partial F-test (Extra Sum of Squares)</h2>
<ul>
<li>The partial F-test is used when a subset of <span class="math inline">\(k\)</span> predictors does not have statistically significant slopes. In other words, it examines a reduced model with <span class="math inline">\(g\)</span> of the <span class="math inline">\(k\)</span> predictors.</li>
<li><strong>Hypotheses</strong>:
<ul>
<li><span class="math inline">\(H_0\)</span>: The extra <span class="math inline">\(k-g\)</span> predictors do not contribute. (All their slopes are zero.)<br>
</li>
<li><span class="math inline">\(H_a\)</span>: At least one of the extra predictors has a nonzero slope.</li>
</ul></li>
<li>This test simultaneously evaluates whether additional predictors improve the model.</li>
</ul>
<section id="example-partial-f-test-using-extra-sum-of-squares" class="level3 example">
<h3 class="anchored" data-anchor-id="example-partial-f-test-using-extra-sum-of-squares">Example: Partial F-test Using Extra Sum of Squares</h3>
<p><strong>Full model</strong>:<br>
<span class="math inline">\(\log(\text{cost}) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + \beta_4 X_4 + \beta_5 X_5 + \beta_6 X_6\)</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th>DF</th>
<th>SS</th>
<th>MS</th>
<th>F</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td>6</td>
<td>1532</td>
<td>255</td>
<td>164</td>
<td>&lt;0.0001</td>
</tr>
<tr class="even">
<td>Error</td>
<td>778</td>
<td>1208</td>
<td>1.55</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>784</td>
<td>2740</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Reduced model</strong>:<br>
<span class="math inline">\(\log(\text{cost}) = \beta_0 + \beta_3 X_3 + \beta_5 X_5 + \beta_6 X_6\)</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th>DF</th>
<th>SS</th>
<th>MS</th>
<th>F</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td>3</td>
<td>1523</td>
<td>508</td>
<td>326</td>
<td>&lt;0.0001</td>
</tr>
<tr class="even">
<td>Error</td>
<td>781</td>
<td>1217</td>
<td>1.56</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>784</td>
<td>2740</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Hypotheses</strong>:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The extra coefficients are all zero (e.g., <span class="math inline">\(\beta_1 = \beta_2 = \beta_4 = 0\)</span>).<br>
</li>
<li><span class="math inline">\(H_a\)</span>: At least one of the extra coefficients is nonzero.</li>
</ul>
<p><strong>Partial F-test comparison</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Error DF</th>
<th>SSE</th>
<th>MSE</th>
<th>F</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td>3</td>
<td>9</td>
<td>3</td>
<td>1.94</td>
<td>0.1216</td>
</tr>
<tr class="even">
<td>Full (Error)</td>
<td>778</td>
<td>1208</td>
<td>1.55</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Reduced (Total)</td>
<td>781</td>
<td>1217</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Partial F-test results</strong>:</p>
<ul>
<li>Critical value (<span class="math inline">\(\alpha = 0.05\)</span>): <span class="math inline">\(F_{0.05, 3, 778} = 2.62\)</span></li>
<li>Observed statistic: <span class="math inline">\(F = 1.94\)</span><br>
</li>
<li>Right-tail <em>p</em>-value: <span class="math inline">\(p = 0.1216\)</span><br>
</li>
<li>Decision: Since <span class="math inline">\(F_{\text{obs}} &lt; F_{\text{crit}}\)</span> and <span class="math inline">\(p &gt; 0.05\)</span>, fail to reject <span class="math inline">\(H_0\)</span>.</li>
</ul>
<p><strong>Interpretation</strong>:<br>
There is not enough evidence to suggest that the extra predictors (e.g., <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, <span class="math inline">\(X_4\)</span>) explain a significant additional portion of variability in <span class="math inline">\(\log(\text{cost})\)</span> beyond the reduced model.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fch12_partial_f_test_tail.png" class="img-fluid figure-img"></p>
<figcaption><strong>Partial F-test.</strong> F-distribution with <span class="math inline">\(df_1=3\)</span> and <span class="math inline">\(df_2=778\)</span> for the partial F-test. The vertical dashed line marks the observed statistic (<span class="math inline">\(F = 1.94\)</span>), and the shaded region shows the right-tail <em>p</em>-value. For <span class="math inline">\(\alpha = 0.05\)</span>, the critical value is <span class="math inline">\(F_{0.05, 3, 778} \approx 2.62\)</span>.</figcaption>
</figure>
</div>
</section>
</section>
<section id="significance-tests-for-each-predictor-t-tests" class="level2">
<h2 class="anchored" data-anchor-id="significance-tests-for-each-predictor-t-tests">Significance Tests for Each Predictor (<em>t</em>-tests)</h2>
<ul>
<li><strong>Hypotheses</strong>:
<ul>
<li><span class="math inline">\(H_0: \beta_i = 0\)</span> (the predictor has no effect).<br>
</li>
<li><span class="math inline">\(H_a: \beta_i \neq 0\)</span> (the predictor has an effect).</li>
</ul></li>
<li><strong>Test statistic</strong>: <span class="math display">\[
t = \frac{b_i}{SE_{b_i}}, \quad df = n - k - 1
\]</span></li>
<li><strong>Standard error calculation</strong>: <span class="math display">\[
SE = \frac{\hat{\sigma}}{\sqrt{\sum_{i=1}^{n} (X_i - \bar{X})^2}}, \quad \hat{\sigma} = \sqrt{\frac{\text{SSR}}{n - k - 1}}
\]</span></li>
</ul>
</section>
<section id="prediction-in-mlr" class="level2">
<h2 class="anchored" data-anchor-id="prediction-in-mlr">Prediction in MLR</h2>
<ul>
<li>Predicted values in MLR are the same as estimated means.<br>
</li>
<li>To obtain confidence intervals for the mean or prediction intervals for individual predictions, statistical software must be used because all variables in the model must be specified.</li>
</ul>
</section>
<section id="least-squares-estimates-and-standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates-and-standard-errors">Least Squares Estimates and Standard Errors</h2>
<ul>
<li>The least squares estimates of the <span class="math inline">\(\beta\)</span>s appear in the coefficient column of the parameter estimate table.</li>
<li>The estimate of <span class="math inline">\(\sigma^2\)</span> is calculated as: <span class="math display">\[
\frac{\text{sum of squared residuals (SSE)}}{\text{df} (n-p)} = \text{MSE}
\]</span></li>
<li>The square root of MSE gives the residual standard error (or RMSE).</li>
</ul>
</section>
<section id="testing-intercept-and-slope-differences-in-regression-models-bat-echolocation-example" class="level2 example">
<h2 class="anchored" data-anchor-id="testing-intercept-and-slope-differences-in-regression-models-bat-echolocation-example">Testing Intercept and Slope Differences in Regression Models (Bat Echolocation Example)</h2>
<section id="question-of-interest-1-equality-of-slopes-across-all-groups" class="level3">
<h3 class="anchored" data-anchor-id="question-of-interest-1-equality-of-slopes-across-all-groups">Question of Interest 1: Equality of Slopes Across All Groups</h3>
<p><strong>Question</strong>: Are the slopes equal across all three groups—birds, echolocating bats (Ebat), and non-echolocating bats (NEbat)—after accounting for body size?</p>
<p><strong>Approach</strong>:<br>
We use an <strong>Extra Sum of Squares F-test</strong>. If slopes are equal (holding body mass constant), the estimated difference in energy expenditure should be the same across groups.</p>
<p><strong>Full model</strong>: <span class="math display">\[
\begin{aligned}
\mu(\text{lenergy} \mid \text{lmass}, \text{TYPE})
&amp;= \beta_0 + \beta_2 \,\text{bird} + \beta_3 \,\text{Ebat} + \beta_1 \,\text{lmass} \\
&amp;\quad + \beta_4 (\text{lmass} \times \text{bird}) + \beta_5 (\text{lmass} \times \text{Ebat})
\end{aligned}
\]</span></p>
<p><strong>Alternative expression</strong>: <span class="math display">\[
\mu(\text{lenergy} \mid \text{lmass}, \text{TYPE}) =
(\beta_0 + \beta_2 \,\text{bird} + \beta_3 \,\text{Ebat}) +
(\beta_1 + \beta_4 \,\text{bird} + \beta_5 \,\text{Ebat}) \,\text{lmass}
\]</span></p>
<p><strong>Group-specific models</strong>: <span class="math display">\[
\begin{aligned}
\text{NEbat:} &amp; \quad \mu = \beta_0 + \beta_1\,\text{lmass} &amp;\quad &amp;\text{slope: } \beta_1 \\
\text{Ebat:}  &amp; \quad \mu = (\beta_0 + \beta_3) + (\beta_1 + \beta_5)\,\text{lmass} &amp;\quad &amp;\text{slope: } \beta_1 + \beta_5 \\
\text{bird:}  &amp; \quad \mu = (\beta_0 + \beta_2) + (\beta_1 + \beta_4)\,\text{lmass} &amp;\quad &amp;\text{slope: } \beta_1 + \beta_4
\end{aligned}
\]</span></p>
<p><strong>Hypotheses</strong>:<br>
<span class="math display">\[
\begin{aligned}
H_0 &amp;: \text{The slopes are equal}
      &amp;&amp;\Leftrightarrow \beta_1 = \beta_1 + \beta_5 = \beta_1 + \beta_4 \\
     &amp; &amp;&amp;\implies \beta_4 = \beta_5 = 0 \quad\text{(lines are parallel)} \\
H_a &amp;: \text{The slopes are not all equal}
      &amp;&amp;\Leftrightarrow \beta_4 \text{ and } \beta_5 \text{ are not both zero}
\end{aligned}
\]</span></p>
<section id="extra-sum-of-squares-f-test" class="level4">
<h4 class="anchored" data-anchor-id="extra-sum-of-squares-f-test">Extra Sum of Squares F-test</h4>
<p>The tables below show the full model, reduced model, and Extra Sum of Squares results used to test whether slopes differ among birds, Ebats, and NEbats.</p>
<p><strong>Full Model ANOVA Table</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 25%">
<col style="width: 20%">
<col style="width: 16%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>DF</th>
<th>Sum of Squares</th>
<th>Mean Square</th>
<th>F Value</th>
<th>Pr &gt; F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td>5</td>
<td>29.4699</td>
<td>5.8940</td>
<td>163.44</td>
<td>&lt;.0001</td>
</tr>
<tr class="even">
<td>Error</td>
<td>14</td>
<td>0.5049</td>
<td>0.0361</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Corrected Total</td>
<td>19</td>
<td>29.9748</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Reduced Model ANOVA Table</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 25%">
<col style="width: 20%">
<col style="width: 16%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>DF</th>
<th>Sum of Squares</th>
<th>Mean Square</th>
<th>F Value</th>
<th>Pr &gt; F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td>3</td>
<td>29.4215</td>
<td>9.8072</td>
<td>283.59</td>
<td>&lt;.0001</td>
</tr>
<tr class="even">
<td>Error</td>
<td>16</td>
<td>0.5533</td>
<td>0.0346</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Corrected Total</td>
<td>19</td>
<td>29.9748</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Extra Sum of Squares Table</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 25%">
<col style="width: 20%">
<col style="width: 16%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>DF</th>
<th>Sum of Squares</th>
<th>Mean Square</th>
<th>F Value</th>
<th>Pr &gt; F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td>2</td>
<td>0.0484</td>
<td>0.0242</td>
<td>0.6704</td>
<td>0.5272</td>
</tr>
<tr class="even">
<td>Error (Full)</td>
<td>14</td>
<td>0.5049</td>
<td>0.0361</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total (Reduced)</td>
<td>16</td>
<td>0.5533</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Interpretation</strong>: From the output, there is not enough evidence to suggest that the lines are not parallel and have different slopes, <em>p</em>-value = 0.5272 from the Extra Sum of Squares F-test.</p>
</section>
</section>
</section>
<section id="question-of-interest-2-equality-of-intercepts-for-bat-types" class="level3 example">
<h3 class="anchored" data-anchor-id="question-of-interest-2-equality-of-intercepts-for-bat-types">Question of Interest 2: Equality of Intercepts for Bat Types</h3>
<p><strong>Question</strong>: Are the intercepts for Ebat and NEbat different after knowing that the slopes are equal?</p>
<p><strong>Hypotheses</strong>:<br>
<span class="math display">\[
\begin{aligned}
H_0 &amp;: \text{The intercepts are equal}
      &amp;&amp;\Leftrightarrow \beta_3 = 0 \quad \text{(no difference between NEbat and Ebat)} \\
H_a &amp;: \text{The intercepts are not all equal}
      &amp;&amp;\Leftrightarrow \beta_3 \neq 0
\end{aligned}
\]</span></p>
<p>Equivalent form of <span class="math inline">\(H_0\)</span> in intercept terms: <span class="math display">\[
\begin{aligned}
&amp;\text{If the intercept for Ebat is equal to that of NEbat,} \\
&amp;\text{then } \beta_0 + \beta_3 = \beta_0 \quad \text{or} \quad \beta_3 = 0
\end{aligned}
\]</span></p>
<div class="figure-caption">
<p><strong>Parameter Estimate Table</strong></p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 13%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Estimate</th>
<th>Standard Error</th>
<th>t Value</th>
<th>Pr &gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-1.5764</td>
<td>0.2872</td>
<td>-5.49</td>
<td>&lt;.0001</td>
</tr>
<tr class="even">
<td>lmass</td>
<td>0.8150</td>
<td>0.0445</td>
<td>18.30</td>
<td>&lt;.0001</td>
</tr>
<tr class="odd">
<td>Type Ebat</td>
<td>0.0787</td>
<td>0.2027</td>
<td>0.39</td>
<td>0.7030</td>
</tr>
<tr class="even">
<td>Type bird</td>
<td>0.1023</td>
<td>0.1142</td>
<td>0.90</td>
<td>0.3837</td>
</tr>
<tr class="odd">
<td>Type NEbat</td>
<td>0.0000</td>
<td>.</td>
<td>.</td>
<td>.</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation</strong>:<br>
Data are consistent with the hypothesis of equal intercepts between Ebat and NEbat after accounting for mass (<em>p</em>-value = 0.7030).</p>
</section>
<section id="variance-of-the-sum-and-difference-of-random-variables" class="level3">
<h3 class="anchored" data-anchor-id="variance-of-the-sum-and-difference-of-random-variables">Variance of the Sum and Difference of Random Variables</h3>
<p>The variance of a linear combination of two random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is:</p>
<p><span class="math display">\[
\text{Var}(aX + bY) = a^2 \,\text{Var}(X) + b^2 \,\text{Var}(Y) + 2ab\,\text{Cov}(X, Y)
\]</span></p>
<p>Covariance (<span class="math inline">\(\text{Cov}\)</span>) measures how two variables move together: positive (<span class="math inline">\(+\)</span>), none (<span class="math inline">\(0\)</span>), or negative (<span class="math inline">\(-\)</span>).</p>
<section id="example-with-regression-coefficients" class="level4">
<h4 class="anchored" data-anchor-id="example-with-regression-coefficients">Example with Regression Coefficients</h4>
<p>Let <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> be regression estimates, treated as random variables.<br>
We obtain their variances by squaring the <span class="math inline">\(\text{SE}\)</span> values from the parameter estimate table.</p>
<p><strong>Sum</strong>: <span class="math display">\[
\begin{aligned}
\text{Var}(\beta_1 + \beta_2) &amp;= 1^2 \, \text{Var}(\beta_1) + 1^2 \, \text{Var}(\beta_2) + 2(1)(1)\text{Cov}(\beta_1, \beta_2) \\
&amp;= \text{Var}(\beta_1) + \text{Var}(\beta_2) + 2 \, \text{Cov}(\beta_1, \beta_2) \\
\end{aligned}
\]</span></p>
<p><strong>Difference</strong>: <span class="math display">\[
\begin{aligned}
\text{Var}(\beta_1 - \beta_2) &amp;= 1^2 \, \text{Var}(\beta_1) + (-1)^2 \, \text{Var}(\beta_2) + 2(1)(-1)\text{Cov}(\beta_1, \beta_2) \\
&amp;= \text{Var}(\beta_1) + \text{Var}(\beta_2) - 2 \, \text{Cov}(\beta_1, \beta_2)
\end{aligned}
\]</span></p>
<p>We will use the difference formula for the next question of interest.</p>
</section>
</section>
<div class="example">
<section id="question-of-interest-3-confidence-interval-for-the-difference-in-intercepts-birds-vs.-ebats" class="level3">
<h3 class="anchored" data-anchor-id="question-of-interest-3-confidence-interval-for-the-difference-in-intercepts-birds-vs.-ebats">Question of Interest 3: Confidence Interval for the Difference in Intercepts (Birds vs.&nbsp;Ebats)</h3>
<p>We want a 95% confidence interval for the difference in intercepts between birds and Ebats after accounting for mass.</p>
<p><strong>Model equation</strong>:<br>
<span class="math display">\[
\text{lenergy} = \beta_0 + \beta_1\,\text{lmass} + \beta_2\,\text{bird} + \beta_3\,\text{Ebat}
\]</span></p>
<p><strong>Modified regression equations</strong>:</p>
<ul>
<li>Birds: <span class="math inline">\(\mu = (\beta_0 + \beta_2) + \beta_1\,\text{lmass}\)</span><br>
</li>
<li>Ebats: <span class="math inline">\(\mu = (\beta_0 + \beta_3) + \beta_1\,\text{lmass}\)</span></li>
</ul>
<p><strong>Difference in intercepts</strong>:<br>
<span class="math display">\[
(\beta_0 + \beta_2) - (\beta_0 + \beta_3) = \beta_2 - \beta_3
\]</span></p>
<p><strong>95% confidence interval formula</strong>: <span class="math display">\[
\begin{aligned}
&amp;\hat{\beta}_2 - \hat{\beta}_3 \pm t_{0.975,\, 16} \times \text{SE}(\hat{\beta}_2 - \hat{\beta}_3) \\
&amp;\hat{\beta}_2 - \hat{\beta}_3 \pm 2.12 \times 0.155
\end{aligned}
\]</span></p>
<p><strong>Finding the standard error</strong>:</p>
<p>From the parameter estimates table: <span class="math display">\[
\text{Var}(\hat{\beta}_2) = 0.0130, \quad \text{Var}(\hat{\beta}_3) = 0.0410, \quad \text{Cov}(\hat{\beta}_2, \hat{\beta}_3) = 0.0150
\]</span></p>
<p>Apply the difference formula: <span class="math display">\[
\begin{aligned}
\text{Var}(\hat{\beta}_2 - \hat{\beta}_3) &amp;= (1)^2 \, \text{Var}(\hat{\beta}_2) + (-1)^2 \, \text{Var}(\hat{\beta}_3) + 2(1)(-1)\text{Cov}(\hat{\beta}_2, \hat{\beta}_3) \\
&amp;= \text{Var}(\hat{\beta}_2) + \text{Var}(\hat{\beta}_3) - 2 \, \text{Cov}(\hat{\beta}_2, \hat{\beta}_3) \\
&amp;= 0.013 + 0.041 - 2(0.015) = 0.024
\end{aligned}
\]</span></p>
<p>Thus: <span class="math display">\[
\text{SE}(\hat{\beta}_2 - \hat{\beta}_3) = \sqrt{\text{Var}(\hat{\beta}_2 - \hat{\beta}_3)} = \sqrt{0.024} = 0.1549
\]</span></p>
<p><strong>Final 95% CI</strong>:<br>
<span class="math display">\[
\begin{aligned}
\hat{\beta}_2 - \hat{\beta}_3 &amp;\pm 2.12 \times 0.1549 \\
(0.1023 - 0.0787)  &amp;\pm 2.12 \times 0.1549 = (−0.3048, 0.3520)
\end{aligned}
\]</span></p>
<p><strong>Interpretation</strong>:<br>
The 95% CI includes zero, so there is insufficient evidence to conclude a difference in intercepts between birds and Ebats after adjusting for body mass.</p>
</section>
<section id="alternative-comparison-birds-vs.-nebats" class="level3">
<h3 class="anchored" data-anchor-id="alternative-comparison-birds-vs.-nebats">Alternative Comparison: Birds vs.&nbsp;NEbats</h3>
<p>Under the current model coding, <code>Type NEbat</code> is the reference group.<br>
This means the parameter estimates for <code>Type bird</code> and <code>Type Ebat</code> are interpreted relative to NEbats.<br>
If the goal were to compare birds and Ebats directly (as in QOI 3), the model would need to be refit with <code>Type Ebat</code> set as the reference group.</p>
<p>Another way to find the difference in intercepts is to note that in the model:</p>
<p><span class="math display">\[
\mu(\text{lenergy} \mid \text{lmass}, \text{TYPE}) = \beta_0 + \beta_1\,\text{lmass} + \beta_2\,\text{bird} + \beta_3\,\text{Ebat}
\]</span></p>
<p>The difference in intercepts between birds and the reference group (NEbat) is simply:</p>
<p><span class="math display">\[
(\beta_0 + \beta_2) - \beta_0 = \beta_2
\]</span></p>
<p>So you can use the parameter estimate <span class="math inline">\(\hat{\beta}_2\)</span> directly from the table.</p>
<p><strong>Parameter Estimate Table</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 12%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Estimate</th>
<th>Standard Error</th>
<th>t Value</th>
<th>Pr &gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-1.5764</td>
<td>0.2872</td>
<td>-5.49</td>
<td>&lt;.0001</td>
</tr>
<tr class="even">
<td>lmass</td>
<td>0.8150</td>
<td>0.0445</td>
<td>18.30</td>
<td>&lt;.0001</td>
</tr>
<tr class="odd">
<td>Type bird</td>
<td>0.1023</td>
<td>0.1142</td>
<td>0.90</td>
<td>0.3837</td>
</tr>
<tr class="even">
<td>Type Ebat</td>
<td>0.0787</td>
<td>0.2027</td>
<td>0.39</td>
<td>0.7030</td>
</tr>
<tr class="odd">
<td>Type NEbat</td>
<td>0.0000</td>
<td>.</td>
<td>.</td>
<td>.</td>
</tr>
</tbody>
</table>
<p><strong>95% Confidence interval calculation</strong>:<br>
Since we are assuming the lines are parallel, we can use <span class="math inline">\(\hat{\beta}_2\)</span> and its standard error to form the CI.</p>
<p>The 95% CI is:<br>
<span class="math display">\[
0.1023 \pm 2.12 \times 0.1142 = (-0.139, 0.344)
\]</span> <strong>Interpretation</strong>: Since the interval contains zero, there is no significant difference in mean energy between birds and NEbats after accounting for mass.</p>
</section>
</div>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./foundation-chapter11.html" class="pagination-link" aria-label="Multiple Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Multiple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./foundation-chapter13.html" class="pagination-link" aria-label="Model Selection and Validation">
        <span class="nav-page-text"><span class="chapter-title">Model Selection and Validation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>